# -*- coding: utf-8 -*-
"""Part1_preferences_And_Network.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYO1iGQEKGd7EBbJADu9asp0ikfoDoAp
"""

# -*- coding: utf-8 -*-
from preflibtools.instances.sampling import generate_IC, generate_mallows_mix
import networkx as nx
import csv
from collections import Counter

# ── Configuration ──────────────────────────────────────────────────────────────
POPULATION_SIZES = [1000, 3000, 5000]
N_CANDIDATES = 12
CANDIDATES   = [
    "Macron", "LePen", "Melenchon", "Zemmour", "Pecresse",
    "Jadot", "Lassalle", "Roussel", "DupontAignan",
    "Hidalgo", "Poutou", "Arthaud"
]
SEED = 42

# ── Reusable helper: expand vote_map + save to CSV ─────────────────────────────
def save_preferences(vote_map, filename, n_voters):
    rows = []
    voter_id = 0
    for order, count in vote_map.items():
        for _ in range(count):
            ranking = [CANDIDATES[tup[0]] for tup in order]
            rows.append([voter_id] + ranking)
            voter_id += 1

    header = ["voter_id"] + [f"rank_{i+1}" for i in range(N_CANDIDATES)]
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)

    top_choices = Counter(row[1] for row in rows)
    print(f"  → Saved: {filename} ({len(rows)} voters)")
    return rows

# ── Helper: save any graph to CSV ─────────────────────────────────────────────
def save_network(G, filename):
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["source", "target"])
        for u, v in G.edges():
            writer.writerow([u, v])
    print(f"  → Saved: {filename} (Edges: {G.number_of_edges()})")

# ── Main Loop: Generate for specific population sizes ─────────────────────────
for N in POPULATION_SIZES:
    print(f"\n{'='*40}")
    print(f"GENERATING DATA FOR N = {N} VOTERS")
    print(f"{'='*40}")

    # --- PREFERENCES (IC & MALLOWS only) ---
    print("\n[Preferences]")
    vote_map_ic = generate_IC(num_voters=N, num_alternatives=N_CANDIDATES)
    save_preferences(vote_map_ic, f"preferences_IC_{N}.csv", N)

    vote_map_mallows = generate_mallows_mix(num_voters=N, num_alternatives=N_CANDIDATES, num_references=3, norm_phi=True)
    save_preferences(vote_map_mallows, f"preferences_MALLOWS_{N}.csv", N)

    # --- NETWORKS (ER & BA only) ---
    print("\n[Networks]")
    p_er = 12.0 / N
    G_er = nx.erdos_renyi_graph(n=N, p=p_er, seed=SEED)
    save_network(G_er, f"network_ER_{N}.csv")

    G_ba = nx.barabasi_albert_graph(n=N, m=3, seed=SEED)
    save_network(G_ba, f"network_BA_{N}.csv")

print("\n All specified data generation complete!")

import zipfile
from google.colab import files

# Create a zip file
zip_filename = "simulation_data.zip"
with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for N in [1000, 3000, 5000]:
        zipf.write(f"preferences_IC_{N}.csv")
        zipf.write(f"preferences_MALLOWS_{N}.csv")
        zipf.write(f"network_ER_{N}.csv")
        zipf.write(f"network_BA_{N}.csv")

print(f"Packaged all files into {zip_filename}. Downloading now...")
files.download(zip_filename)